server:
  port: 3021
spring:
  application:
    name: cart-service
  cloud:
    openfeign:
      client:
        config:
          default:
            readTimeout: 3000
            connectTimeout: 10000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: notes
    username: root
    url: jdbc:mysql://127.0.0.1:3306/shopping_cart
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
